# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/basic3.ui'
#
# Created: Thu Aug 14 14:48:14 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(805, 422)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.group_player = QtGui.QGroupBox(self.centralwidget)
        self.group_player.setGeometry(QtCore.QRect(340, 20, 251, 241))
        self.group_player.setCheckable(True)
        self.group_player.setChecked(False)
        self.group_player.setObjectName(_fromUtf8("group_player"))
        self.button_start = QtGui.QPushButton(self.group_player)
        self.button_start.setGeometry(QtCore.QRect(0, 80, 251, 27))
        self.button_start.setObjectName(_fromUtf8("button_start"))
        self.label_2 = QtGui.QLabel(self.group_player)
        self.label_2.setGeometry(QtCore.QRect(140, 30, 51, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_total_time = QtGui.QLabel(self.group_player)
        self.label_total_time.setGeometry(QtCore.QRect(200, 30, 48, 16))
        self.label_total_time.setObjectName(_fromUtf8("label_total_time"))
        self.label_3 = QtGui.QLabel(self.group_player)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 48, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.group_player)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 51, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.line = QtGui.QFrame(self.group_player)
        self.line.setGeometry(QtCore.QRect(0, 110, 251, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_5 = QtGui.QLabel(self.group_player)
        self.label_5.setGeometry(QtCore.QRect(0, 130, 71, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.text_log = QtGui.QPlainTextEdit(self.group_player)
        self.text_log.setGeometry(QtCore.QRect(0, 150, 251, 84))
        self.text_log.setReadOnly(True)
        self.text_log.setCenterOnScroll(True)
        self.text_log.setObjectName(_fromUtf8("text_log"))
        self.group_list = QtGui.QGroupBox(self.centralwidget)
        self.group_list.setGeometry(QtCore.QRect(10, 0, 301, 271))
        self.group_list.setTitle(_fromUtf8(""))
        self.group_list.setObjectName(_fromUtf8("group_list"))
        self.list_list = QtGui.QListWidget(self.group_list)
        self.list_list.setGeometry(QtCore.QRect(0, 30, 256, 192))
        self.list_list.setObjectName(_fromUtf8("list_list"))
        self.button_save_list = QtGui.QPushButton(self.group_list)
        self.button_save_list.setEnabled(False)
        self.button_save_list.setGeometry(QtCore.QRect(180, 240, 85, 27))
        self.button_save_list.setObjectName(_fromUtf8("button_save_list"))
        self.button_new_list = QtGui.QPushButton(self.group_list)
        self.button_new_list.setGeometry(QtCore.QRect(0, 240, 85, 27))
        self.button_new_list.setObjectName(_fromUtf8("button_new_list"))
        self.button_add = QtGui.QPushButton(self.group_list)
        self.button_add.setEnabled(False)
        self.button_add.setGeometry(QtCore.QRect(270, 100, 21, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(70)
        self.button_add.setFont(font)
        self.button_add.setObjectName(_fromUtf8("button_add"))
        self.button_load_list = QtGui.QPushButton(self.group_list)
        self.button_load_list.setGeometry(QtCore.QRect(90, 240, 81, 27))
        self.button_load_list.setObjectName(_fromUtf8("button_load_list"))
        self.label_queue_name = QtGui.QLabel(self.group_list)
        self.label_queue_name.setGeometry(QtCore.QRect(80, 10, 201, 16))
        self.label_queue_name.setObjectName(_fromUtf8("label_queue_name"))
        self.button_remove = QtGui.QPushButton(self.group_list)
        self.button_remove.setEnabled(False)
        self.button_remove.setGeometry(QtCore.QRect(270, 130, 21, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_remove.setFont(font)
        self.button_remove.setObjectName(_fromUtf8("button_remove"))
        self.button_up = QtGui.QToolButton(self.group_list)
        self.button_up.setEnabled(False)
        self.button_up.setGeometry(QtCore.QRect(270, 30, 21, 24))
        self.button_up.setArrowType(QtCore.Qt.UpArrow)
        self.button_up.setObjectName(_fromUtf8("button_up"))
        self.button_down = QtGui.QToolButton(self.group_list)
        self.button_down.setEnabled(False)
        self.button_down.setGeometry(QtCore.QRect(270, 60, 21, 24))
        self.button_down.setArrowType(QtCore.Qt.DownArrow)
        self.button_down.setObjectName(_fromUtf8("button_down"))
        self.label = QtGui.QLabel(self.group_list)
        self.label.setGeometry(QtCore.QRect(0, 10, 81, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(310, 10, 20, 261))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 605, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menu_animation_new = QtGui.QAction(MainWindow)
        self.menu_animation_new.setObjectName(_fromUtf8("menu_animation_new"))
        self.menuAnimation = QtGui.QMenu(self.menubar)
        self.menuAnimation.setObjectName(_fromUtf8("menuAnimation"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionEdit = QtGui.QAction(MainWindow)
        self.actionEdit.setObjectName(_fromUtf8("actionEdit"))
        self.actionLoad_from_file = QtGui.QAction(MainWindow)
        self.actionLoad_from_file.setObjectName(_fromUtf8("actionLoad_from_file"))
        self.actionSave_file = QtGui.QAction(MainWindow)
        self.actionSave_file.setObjectName(_fromUtf8("actionSave_file"))
        self.menu_load_list = QtGui.QAction(MainWindow)
        self.menu_load_list.setObjectName(_fromUtf8("menu_load_list"))
        self.menu_new_list = QtGui.QAction(MainWindow)
        self.menu_new_list.setObjectName(_fromUtf8("menu_new_list"))
        self.menu_save_list = QtGui.QAction(MainWindow)
        self.menu_save_list.setEnabled(False)
        self.menu_save_list.setObjectName(_fromUtf8("menu_save_list"))
        self.menu_animation_edit = QtGui.QAction(MainWindow)
        self.menu_animation_edit.setObjectName(_fromUtf8("menu_animation_edit"))
        self.menu_quit = QtGui.QAction(MainWindow)
        self.menu_quit.setObjectName(_fromUtf8("menu_quit"))
        self.menuFile.addAction(self.menu_new_list)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menu_load_list)
        self.menuFile.addAction(self.menu_save_list)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menu_quit)
        self.menuAnimation.addAction(self.menu_animation_new)
        self.menuAnimation.addAction(self.menu_animation_edit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAnimation.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Animation Player", None, QtGui.QApplication.UnicodeUTF8))
        self.group_player.setTitle(QtGui.QApplication.translate("MainWindow", "Animation player", None, QtGui.QApplication.UnicodeUTF8))
        self.button_start.setText(QtGui.QApplication.translate("MainWindow", "Compile animation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Total time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_total_time.setText(QtGui.QApplication.translate("MainWindow", "00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Executed:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Remaining:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Execution log", None, QtGui.QApplication.UnicodeUTF8))
        self.button_save_list.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.button_new_list.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.button_add.setToolTip(QtGui.QApplication.translate("MainWindow", "Add animation to queue", None, QtGui.QApplication.UnicodeUTF8))
        self.button_add.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.button_load_list.setText(QtGui.QApplication.translate("MainWindow", "Load...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_queue_name.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.button_remove.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove selected animation", None, QtGui.QApplication.UnicodeUTF8))
        self.button_remove.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.button_up.setToolTip(QtGui.QApplication.translate("MainWindow", "Move animation up", None, QtGui.QApplication.UnicodeUTF8))
        self.button_up.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.button_down.setToolTip(QtGui.QApplication.translate("MainWindow", "Move animation down", None, QtGui.QApplication.UnicodeUTF8))
        self.button_down.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Animations list:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAnimation.setTitle(QtGui.QApplication.translate("MainWindow", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_from_file.setText(QtGui.QApplication.translate("MainWindow", "Load from file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_file.setText(QtGui.QApplication.translate("MainWindow", "Export to file", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_load_list.setText(QtGui.QApplication.translate("MainWindow", "Load list...", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_load_list.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_new_list.setText(QtGui.QApplication.translate("MainWindow", "New list", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_new_list.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_animation_new.setText(QtGui.QApplication.translate("MainWindow", "New...", None, QtGui.QApplication.UnicodeUTF8))

        self.menu_save_list.setText(QtGui.QApplication.translate("MainWindow", "Save list", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_save_list.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_animation_edit.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_quit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_quit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

